// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjQXdpIcIVRt6R9NYmDJAOmmRbWo4d3o',
    appId: '1:630843716019:web:9f9b6481ad3fed93355bc6',
    messagingSenderId: '630843716019',
    projectId: 'movie-recommender-51345',
    authDomain: 'movie-recommender-51345.firebaseapp.com',
    storageBucket: 'movie-recommender-51345.appspot.com',
    measurementId: 'G-PFNX65XXJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqN5JH7ePfe1JCe823kJQtsToUlXwFGKk',
    appId: '1:630843716019:android:f7af547788703f8c355bc6',
    messagingSenderId: '630843716019',
    projectId: 'movie-recommender-51345',
    storageBucket: 'movie-recommender-51345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOssmSrzylaUocx5fS4szwjt-rG32FWQ',
    appId: '1:630843716019:ios:359062cc197656be355bc6',
    messagingSenderId: '630843716019',
    projectId: 'movie-recommender-51345',
    storageBucket: 'movie-recommender-51345.appspot.com',
    iosBundleId: 'org.movierecommenderapp.br',
  );
}
